### ISSUE TITLE
Mpi tests finish successfully even thought there are errors in the launched MPI processes

### ISSUE THREAD

**Issue by fverdugo** [gridap/GridapPETSc.jl#71]
See e.g. https://github.com/gridap/GridapPETSc.jl/runs/4934759266?check_suite_focus=true#step:9:1942

**Comment by fverdugo** [comment]
@amartinhuertas I think this is important to fix. Any ideas?

**Comment by amartinhuertas** [comment]
Hi @fverdugo! Thanks for reporting. 

I was aware of this problem, but I did not have much time to spend in it yet.  I fully agree we need a solution here. 

The problem is caused by the following line 

https://github.com/gridap/GridapPETSc.jl/blob/master/test/mpi/mpiexec.jl#L13

As far as I remember, I did not add that line. I just assumed that someone had trouble before with `mpirun` not returning true even with a succesful execution, and have lived with it so far.  Do you remember why that line is there?

**Comment by amartinhuertas** [comment]
BTW, we have the same pitfall in GridapDistributed, https://github.com/gridap/GridapDistributed.jl/blob/master/test/mpi/runtests.jl#L24
